# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [48]:
import numpy as np

arr = np.random.uniform(0, 20, size=(4, 7))

# минимальное и максимальное значение
min_val = np.min(arr)
max_val = np.max(arr)

# параметры нормализации
a = 1 / (max_val - min_val)
b = -a * min_val

# нормализация
normalized_arr = a * arr + b

print("Исходный:")
print(arr)
print("Нормализованный:")
print(normalized_arr)

Исходный:
[[ 7.82114373  3.31492048 19.78607562  3.98925179  5.85213825  6.75168143
   6.84600316]
 [ 1.57898754 15.81617358  7.04618531  1.78994132 14.30388368 12.75040561
  19.78050216]
 [14.70329605  2.14105613 17.75248094 16.55506773 11.75386675 18.93285758
  18.19769278]
 [14.40538457  9.05109173 19.24796105 10.85793362  4.53447404 19.3232198
   1.0139266 ]]
Нормализованный:
[[0.36262322 0.12257488 1.         0.15849678 0.2577335  0.30565253
  0.31067709]
 [0.03010103 0.78852171 0.32134087 0.04133862 0.70796141 0.625207
  0.9997031 ]
 [0.72923827 0.06004265 0.89166959 0.8278829  0.57212097 0.95454873
  0.9153862 ]
 [0.7133684  0.42814305 0.97133442 0.52439425 0.18754099 0.97534348
  0.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [49]:
import numpy as np

matrix = np.random.randint(0, 11, size=(8, 10))

# суммы значений по каждой строке
r_sums = np.sum(matrix, axis=1)

# минимальная сумма
min_sum_row_index = np.argmin(row_sums)

print(f"Строка с min суммой значений (индекс {min_sum_row_index}):")
print(matrix[min_sum_row_index])

Строка с min суммой значений (индекс 0):
[ 6 10  2  4  7  8  9  2  3  6]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [50]:
import numpy as np

def euclidean_distance(q, w):
    if len(q) != len(w):
        raise ValueError("Векторы должны иметь одинаковую размерность")
    
    # квадрат разности каждой пары элементов и их сумма
    squared_diff = np.sum((q - w) ** 2)
    
    # квадратный корень
    distance = np.sqrt(squared_diff)
    return distance

q = np.array([1, 2, 3])
w = np.array([4, 5, 6])
distance = euclidean_distance(q, w)
print(distance)


5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [51]:
import numpy as np

A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

# обратные матрицы
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

# находим х
X = -np.dot(np.dot(A_inv, C), B_inv)

print(X)

[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [27]:
import numpy as np

# данные из файла
data = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)

print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [32]:
import numpy as np

data = np.array([[127244, 60, 16],
                 [23891, 25, 7],
                 [94746, 10, 6],
                 [67660, 5, 6],
                 [157911, 60, 14]])

# срез для исключения 1-го столбца
data_without_first_column = data[:, 1:]

mean_val = np.mean(data_without_first_column, axis=0)
min_val = np.min(data_without_first_column, axis=0)
max_val = np.max(data_without_first_column, axis=0)
median_val = np.median(data_without_first_column, axis=0)

print("Среднее:", mean_val)
print("Минимум:", min_val)
print("Максимум:", max_val)
print("Медиана:", median_val)

Среднее: [32.   9.8]
Минимум: [5 6]
Максимум: [60 16]
Медиана: [25.  7.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [1]:
import pandas as pd

df = pd.read_csv('minutes_n_ingredients.csv')

quantile_75 = df['minutes'].quantile(0.75)

# Ограничение спомощью clip()
df['minutes'] = df['minutes'].clip(upper=quantile_75)

print(df.head())

       id  minutes  n_ingredients
0  127244       60             16
1   23891       25              7
2   94746       10              6
3   67660        5              6
4  157911       60             14


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [34]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

# индекс продолжительности
duration_index = 1

# кол-вл по продолжительности = 0
zero_duration_count = np.sum(data[:, duration_index] == 0)

print(zero_duration_count)

# замена на 1
data[data[:, duration_index] == 0, duration_index] = 1

# сохранение новых данных
# np.savetxt('updated_minutes_n_ingredients.csv', data, delimiter=',', fmt='%d')

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [35]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

recipe_id_index = 0

# получение идентификаторов
unique_recipe_ids = np.unique(data[:, recipe_id_index])

num_unique_recipes = len(unique_recipe_ids)

print(num_unique_recipes)

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [36]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

# кол-во ингредиентов
ingredients_count_index = 2

# уникальные значения
unique_ingredients_counts = np.unique(data[:, ingredients_count_index])

num_unique_ingredients_counts = len(unique_ingredients_counts)

print("Различные значения количества ингредиентов и их количество:")
for count in unique_ingredients_counts:
    count_occurrences = np.sum(data[:, ingredients_count_index] == count)
    print(f"Ингредиенты: {int(count)}, рецепты: {count_occurrences}")


Различные значения количества ингредиентов и их количество:
Ингредиенты: 1, рецепты: 13
Ингредиенты: 2, рецепты: 926
Ингредиенты: 3, рецепты: 2895
Ингредиенты: 4, рецепты: 5515
Ингредиенты: 5, рецепты: 7913
Ингредиенты: 6, рецепты: 9376
Ингредиенты: 7, рецепты: 10628
Ингредиенты: 8, рецепты: 10951
Ингредиенты: 9, рецепты: 10585
Ингредиенты: 10, рецепты: 9591
Ингредиенты: 11, рецепты: 8297
Ингредиенты: 12, рецепты: 6605
Ингредиенты: 13, рецепты: 4997
Ингредиенты: 14, рецепты: 3663
Ингредиенты: 15, рецепты: 2595
Ингредиенты: 16, рецепты: 1767
Ингредиенты: 17, рецепты: 1246
Ингредиенты: 18, рецепты: 790
Ингредиенты: 19, рецепты: 573
Ингредиенты: 20, рецепты: 376
Ингредиенты: 21, рецепты: 217
Ингредиенты: 22, рецепты: 161
Ингредиенты: 23, рецепты: 105
Ингредиенты: 24, рецепты: 69
Ингредиенты: 25, рецепты: 50
Ингредиенты: 26, рецепты: 28
Ингредиенты: 27, рецепты: 16
Ингредиенты: 28, рецепты: 16
Ингредиенты: 29, рецепты: 12
Ингредиенты: 30, рецепты: 12
Ингредиенты: 31, рецепты: 3
Ингредиенты

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [37]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

ingredients_count_index = 2

# отборка
filtered_data = data[data[:, ingredients_count_index] <= 5]

print(filtered_data)

[[4.46597e+05 1.50000e+01 5.00000e+00]
 [2.04134e+05 5.00000e+00 3.00000e+00]
 [2.56230e+04 6.00000e+00 4.00000e+00]
 ...
 [5.20880e+04 6.00000e+01 5.00000e+00]
 [1.28811e+05 1.50000e+01 4.00000e+00]
 [3.70915e+05 5.00000e+00 4.00000e+00]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [40]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

ingredients_count_index = 2
minutes_index = 1

# проверка продолжительности
nonzero_duration = data[:, minutes_index] > 0

# среднне кол-во ингредиентов на минуту
ingredients_on_minute = np.zeros_like(data[:, minutes_index], dtype=float)
ingredients_on_minute[nonzero_duration_mask] = data[nonzero_duration, ingredients_count_index] / data[nonzero_duration, minutes_index]

max_ingredients_on_minute = np.max(ingredients_on_minute)

print(max_ingredients_on_minute)

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [42]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

ingredients_count_index = 2
minutes_index = 1

# сортировка по убыванию
sorted_data = data[data[:, minutes_index].argsort()[::-1]]

top_100_data = sorted_data[:100]

# среднее кол-во ингредиентов 
mean_ingredients_top_100 = np.mean(top_100_data[:, ingredients_count_index])

print(mean_ingredients_top_100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [43]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', dtype=None, names=True, encoding='utf-8')

# выборкпа
random_indices = np.random.choice(len(data), size=10, replace=False)

for idx in random_indices:
    print(data['id'][idx])
    print("Продолжительность:", data['minutes'][idx], "минут")
    print("Кол-во ингредиентов:", data['n_ingredients'][idx])
    print()


393806
Продолжительность: 75 минут
Кол-во ингредиентов: 7

482344
Продолжительность: 20 минут
Кол-во ингредиентов: 7

441493
Продолжительность: 250 минут
Кол-во ингредиентов: 10

53605
Продолжительность: 30 минут
Кол-во ингредиентов: 6

112610
Продолжительность: 60 минут
Кол-во ингредиентов: 8

290897
Продолжительность: 10 минут
Кол-во ингредиентов: 3

403420
Продолжительность: 35 минут
Кол-во ингредиентов: 12

294295
Продолжительность: 120 минут
Кол-во ингредиентов: 10

140000
Продолжительность: 10 минут
Кол-во ингредиентов: 12

16724
Продолжительность: 70 минут
Кол-во ингредиентов: 5



11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [44]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

ingredients_count_index = 2

# среднее кол-во ингредиентов
mean_ingredients_count = np.mean(data[:, ingredients_count_index])

# кол-во рецептов где кол-во ингредиентов меньше среднего
less_than_mean_count = np.sum(data[:, ingredients_count_index] < mean_ingredients_count)

total_recipes_count = len(data)

# процент рецептов где кол-во ингредиентов меньше среднего
percentage_less_mean = (less_than_mean_count / total_recipes_count) * 100

print(percentage_less_mean, "%")

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [1]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

minutes_index = 1
ingredients_count_index = 2

# условие простого
simple_recipe_condition = (data[:, minutes_index] <= 20) & (data[:, ingredients_count_index] <= 5)

# новый столбец
simple_recipe_column = np.where(simple_recipe_condition, 1, 0)

# добавление к исходникам
data_simple_column = np.column_stack((data, simple_recipe_column))

print(data_simple_column[:5])

[[1.27244e+05 6.00000e+01 1.60000e+01 0.00000e+00]
 [2.38910e+04 2.50000e+01 7.00000e+00 0.00000e+00]
 [9.47460e+04 1.00000e+01 6.00000e+00 0.00000e+00]
 [6.76600e+04 5.00000e+00 6.00000e+00 0.00000e+00]
 [1.57911e+05 6.00000e+01 1.40000e+01 0.00000e+00]]


13. Выведите процент "простых" рецептов в датасете

In [2]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

minutes_index = 1
ingredients_count_index = 2

simple_recipe_condition = (data[:, minutes_index] <= 20) & (data[:, ingredients_count_index] <= 5)

# подсчет простых
simple_recipes_count = np.sum(simple_recipe_condition)

# общий подсчёт 
total_recipes_count = len(data)

# вычисление процента простых
simple_recipes = (simple_recipes_count / total_recipes_count) * 100

print(simple_recipes, "%")

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [52]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)

minutes_index = 1

# фильтр
short_recipes = data[data[:, minutes_index] < 10]
standard_recipes = data[(data[:, minutes_index] >= 10) & (data[:, minutes_index] < 20)]
long_recipes = data[data[:, minutes_index] >= 20]

# определение max ко-во
max_short = min(len(short_recipes), len(standard_recipes), len(long_recipes))
max_standard = max_short
max_long = max_short

# выборка max кол-во
short_recipes = short_recipes[:max_short]
standard_recipes = standard_recipes[:max_standard]
long_recipes = long_recipes[:max_long]

# массив
recipes_array = np.array([short_recipes, standard_recipes, long_recipes])

print(recipes_array.shape)

[[[6.76600e+04 5.00000e+00 6.00000e+00]
  [3.66174e+05 7.00000e+00 9.00000e+00]
  [2.04134e+05 5.00000e+00 3.00000e+00]
  ...
  [4.20725e+05 5.00000e+00 3.00000e+00]
  [4.74700e+03 0.00000e+00 9.00000e+00]
  [3.70915e+05 5.00000e+00 4.00000e+00]]

 [[9.47460e+04 1.00000e+01 6.00000e+00]
  [3.39410e+04 1.80000e+01 9.00000e+00]
  [4.46597e+05 1.50000e+01 5.00000e+00]
  ...
  [9.83100e+03 1.50000e+01 7.00000e+00]
  [3.35859e+05 1.20000e+01 1.40000e+01]
  [2.56812e+05 1.00000e+01 3.00000e+00]]

 [[1.27244e+05 6.00000e+01 1.60000e+01]
  [2.38910e+04 2.50000e+01 7.00000e+00]
  [1.57911e+05 6.00000e+01 1.40000e+01]
  ...
  [1.68901e+05 2.50000e+01 7.00000e+00]
  [3.92339e+05 3.50000e+01 1.30000e+01]
  [2.06732e+05 4.50000e+01 1.00000e+01]]]
